version: '3.9'

services:
  backend:
    image: hasini705/skilllink:backend
    build: ./backend
    container_name: skilllink-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    image: hasini705/skilllink:frontend
    build: ./frontend
    container_name: skilllink-frontend
    ports:
      - "5173:10000"
    depends_on:
      - backend